### ISSUE TITLE
NestedFormInput validation issue

### ISSUE THREAD

**Issue by niuyunsi** [teamious/FormBuilder#104]
**Repro:**

1. When fill out a NestedForm.
2. Fill out the NestedForm.
3. Click Submit button. No error.
4. Add the second entry. Will show error.
5. Delete the first entry.
6. Fill out the second entry.

**Expected behavior:**
No error. Submit button can be clicked.

**Actual behavior:**
No error, but Submit button is disabled. fieldStatus.error is still 'nestedError'.

---

NestedFormInput.tsx line 99

**Comment by linweigao** [comment]
Fixed by #107
