### ISSUE TITLE
Deleted field cache

### ISSUE THREAD

**Issue by asinner** [teamious/FormBuilder#26]
Deleted fields are being cached by editor.

**Repro**:
1. Add a field
2. Click "Edit"  button
3. Click "Remove" button

**Expected behavior**:
The field is deleted and the editor resets. 

**Actual behavior**:
The field stays cached in the editor. When you make an edit to a field that has been removed/cached it will be re-inserted into the form.

**Comment by linweigao** [comment]
By using FormBuilder.onChange: (fields: data.IField[], change: data.IFieldChange) => void. Depends on (change.action === FieldAction.Delete) to determine whether the option selector should reset or not.
