### ISSUE TITLE
Re-ordering fields while editing overwrites original field index.

### ISSUE THREAD

**Issue by asinner** [teamious/FormBuilder#27]
**Repro**:
1. Add two fields
2. Click "Edit" button
3. Re-order fields
4. Modify field via the editor

**Expected Behavior**:
The field is updated as normal.

**Actual Behavior**:
The FormBuilder updates the wrong field. It overwrites the field positioned at the index the edited field started at.

**Comment by linweigao** [comment]
Fixed in https://github.com/teamious/FormBuilder/pull/46.
