### ISSUE TITLE
NestedFormOptionEditor can't get the latest NestedForm.

### ISSUE THREAD

**Issue by niuyunsi** [teamious/FormBuilder#87]
**Repro:**

1. In form builder, select NestedForm to edit NestedForm option.
2. Delete one field in NestedForm.
3. In option editor, edit NestedForm option.

**Expected behavior:**
Option can be edited.

**Actual behavior:**
Option cannot be edited. Error: cannot update field inside fields.

**Comment by linweigao** [comment]
This bug has been fixed by #88
