### ISSUE TITLE
Nested form builder should at least contain one field

### ISSUE THREAD

**Issue by linweigao** [teamious/FormBuilder#92]

**Comment by asinner** [comment]
@linweigao  Should we put this into gigaform instead? Addressing this problem in the core package means implementing business logic like localized error messages and hardcoding the UI for the error message.

**Comment by linweigao** [comment]
@asinner Agreed. Please help to fix this is Gigaform. Since we provide no-fields css already. Maybe gigaform can easily customized the no-fields css.
